### ISSUE TITLE
Please tag a stable release

### ISSUE THREAD

**Issue by sjackman** [lh3/fermi2#1]

**Comment by sjackman** [comment]
Hi, Heng. Would you please tag r188 as a stable release of fermi2? I'd like to package it for Homebrew-science.

**Comment by lh3** [comment]
I have just put a "0.1" tag on r188. Thanks.

**Comment by sjackman** [comment]
Thanks, Heng. See https://github.com/Homebrew/homebrew-science/pull/2217
