### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by runfish5** [lh3/fermi2#5]
Dear Team

Is there a documentation for fermi2 available? Or even a tutorial? I dont understand the capabilities of this program.

I read the Heng Li's post about xz compression ( [http://lh3.github.io/2021/05/17/an-fm-index-of-400k-sars-cov-2-genomes](http://lh3.github.io/2021/05/17/an-fm-index-of-400k-sars-cov-2-genomes) ) In there are some code examples, they seem good and could go into the README.md.

I also have one question respective:
```
# count 61-mers occurring 10 times or more using 4 threads (5 sec on my laptop)
fermi2 count -k61 -o10 -t4 sars-cov-2.fmd | less
```
How low can -k61 go, does it work with -k8 ?

**Comment by lh3** [comment]
-k8 should work.
